// swift-tools-version: 5.9

// WARNING:
// This file is auto-generated by Swift Playgrounds.
// Do not edit this file by hand.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "MedxElite",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "MedxElite",
            targets: ["AppModule"],
            bundleIdentifier: "quest.srihari.medxelite",
            displayVersion: "1.0.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .heart),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .outgoingNetworkConnections()
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
